version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ezt_frontend
    ports:
      - "5000:5000"
    networks:
      - ezt-network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ezt_backend
    ports:
      - "2405:2405"
    networks:
      - ezt-network
    volumes:
      - ./public:/backend/public
    environment:
      - NODE_ENV= production
      - FRONTEND_URL= https://ezticket.io.vn
      - BACKEND_URL= https://ezticket.io.vn

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - ezt-network

networks:
  ezt-network:
    driver: bridge